<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProgramasTodos extends \Entities\ProgramasTodos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'prgCodProg', 'prgNombre', 'prgResumen', 'prgNivel', 'prgTipo', 'prgarea');
        }

        return array('__isInitialized__', 'prgCodProg', 'prgNombre', 'prgResumen', 'prgNivel', 'prgTipo', 'prgarea');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProgramasTodos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPrgarea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrgarea', array());

        return parent::getPrgarea();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrgarea($prgarea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrgarea', array($prgarea));

        return parent::setPrgarea($prgarea);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrgCodProg()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPrgCodProg();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrgCodProg', array());

        return parent::getPrgCodProg();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrgCodProg($prgCodProg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrgCodProg', array($prgCodProg));

        return parent::setPrgCodProg($prgCodProg);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrgNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrgNombre', array());

        return parent::getPrgNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrgNombre($prgNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrgNombre', array($prgNombre));

        return parent::setPrgNombre($prgNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsPrecargas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsPrecargas', array());

        return parent::getAsPrecargas();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsPrecargas($asPrecargas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsPrecargas', array($asPrecargas));

        return parent::setAsPrecargas($asPrecargas);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsHorarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsHorarios', array());

        return parent::getAsHorarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsHorarios($asHorarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsHorarios', array($asHorarios));

        return parent::setAsHorarios($asHorarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioProgramas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioProgramas', array());

        return parent::getUsuarioProgramas();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioProgramas($usuarioProgramas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioProgramas', array($usuarioProgramas));

        return parent::setUsuarioProgramas($usuarioProgramas);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrgResumen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrgResumen', array());

        return parent::getPrgResumen();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrgResumen($prgResumen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrgResumen', array($prgResumen));

        return parent::setPrgResumen($prgResumen);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrgNivel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrgNivel', array());

        return parent::getPrgNivel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrgNivel($prgNivel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrgNivel', array($prgNivel));

        return parent::setPrgNivel($prgNivel);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrgTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrgTipo', array());

        return parent::getPrgTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrgTipo($prgTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrgTipo', array($prgTipo));

        return parent::setPrgTipo($prgTipo);
    }

}
