<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Asistencia extends \Entities\Asistencia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'numero', 'codigo', 'ano', 'periodo', 'programa', 'codJefe', 'asignatura', 'jornada', 'grupo', 'semestre', 'fecha', 'dia', 'semana', 'inicio', 'fin', 'docente', 'estado', 'aula', 'tema', 'cantidad', 'fCreacion', 'uCreacion', 'fRegistro', 'uRegistro', 'fImpresion', 'uImpresion', 'fIngreso', 'fEntrega', 'sede', 'observacion', 'permitir', 'docSustituto');
        }

        return array('__isInitialized__', 'numero', 'codigo', 'ano', 'periodo', 'programa', 'codJefe', 'asignatura', 'jornada', 'grupo', 'semestre', 'fecha', 'dia', 'semana', 'inicio', 'fin', 'docente', 'estado', 'aula', 'tema', 'cantidad', 'fCreacion', 'uCreacion', 'fRegistro', 'uRegistro', 'fImpresion', 'uImpresion', 'fIngreso', 'fEntrega', 'sede', 'observacion', 'permitir', 'docSustituto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Asistencia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getNumero();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', array());

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', array($codigo));

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAno', array());

        return parent::getAno();
    }

    /**
     * {@inheritDoc}
     */
    public function setAno($ano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAno', array($ano));

        return parent::setAno($ano);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodo', array());

        return parent::getPeriodo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodo($periodo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodo', array($periodo));

        return parent::setPeriodo($periodo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrograma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrograma', array());

        return parent::getPrograma();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrograma($programa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrograma', array($programa));

        return parent::setPrograma($programa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodJefe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodJefe', array());

        return parent::getCodJefe();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodJefe($codJefe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodJefe', array($codJefe));

        return parent::setCodJefe($codJefe);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsignatura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsignatura', array());

        return parent::getAsignatura();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsignatura($asignatura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsignatura', array($asignatura));

        return parent::setAsignatura($asignatura);
    }

    /**
     * {@inheritDoc}
     */
    public function getJornada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJornada', array());

        return parent::getJornada();
    }

    /**
     * {@inheritDoc}
     */
    public function setJornada($jornada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJornada', array($jornada));

        return parent::setJornada($jornada);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupo', array());

        return parent::getGrupo();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupo($grupo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupo', array($grupo));

        return parent::setGrupo($grupo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSemestre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSemestre', array());

        return parent::getSemestre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSemestre($semestre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSemestre', array($semestre));

        return parent::setSemestre($semestre);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDia', array());

        return parent::getDia();
    }

    /**
     * {@inheritDoc}
     */
    public function setDia($dia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDia', array($dia));

        return parent::setDia($dia);
    }

    /**
     * {@inheritDoc}
     */
    public function getSemana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSemana', array());

        return parent::getSemana();
    }

    /**
     * {@inheritDoc}
     */
    public function setSemana($semana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSemana', array($semana));

        return parent::setSemana($semana);
    }

    /**
     * {@inheritDoc}
     */
    public function getInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInicio', array());

        return parent::getInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setInicio($inicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInicio', array($inicio));

        return parent::setInicio($inicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFin', array());

        return parent::getFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFin($fin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFin', array($fin));

        return parent::setFin($fin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocente', array());

        return parent::getDocente();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocente($docente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocente', array($docente));

        return parent::setDocente($docente);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getAula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAula', array());

        return parent::getAula();
    }

    /**
     * {@inheritDoc}
     */
    public function setAula($aula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAula', array($aula));

        return parent::setAula($aula);
    }

    /**
     * {@inheritDoc}
     */
    public function getTema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTema', array());

        return parent::getTema();
    }

    /**
     * {@inheritDoc}
     */
    public function setTema($tema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTema', array($tema));

        return parent::setTema($tema);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidad', array());

        return parent::getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidad($cantidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidad', array($cantidad));

        return parent::setCantidad($cantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getFCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFCreacion', array());

        return parent::getFCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFCreacion($fCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFCreacion', array($fCreacion));

        return parent::setFCreacion($fCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUCreacion', array());

        return parent::getUCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUCreacion($uCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUCreacion', array($uCreacion));

        return parent::setUCreacion($uCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFRegistro', array());

        return parent::getFRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setFRegistro($fRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFRegistro', array($fRegistro));

        return parent::setFRegistro($fRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getURegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getURegistro', array());

        return parent::getURegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setURegistro($uRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setURegistro', array($uRegistro));

        return parent::setURegistro($uRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getFImpresion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFImpresion', array());

        return parent::getFImpresion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFImpresion($fImpresion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFImpresion', array($fImpresion));

        return parent::setFImpresion($fImpresion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUImpresion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUImpresion', array());

        return parent::getUImpresion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUImpresion($uImpresion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUImpresion', array($uImpresion));

        return parent::setUImpresion($uImpresion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFIngreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFIngreso', array());

        return parent::getFIngreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setFIngreso($fIngreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFIngreso', array($fIngreso));

        return parent::setFIngreso($fIngreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFEntrega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFEntrega', array());

        return parent::getFEntrega();
    }

    /**
     * {@inheritDoc}
     */
    public function setFEntrega($fEntrega)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFEntrega', array($fEntrega));

        return parent::setFEntrega($fEntrega);
    }

    /**
     * {@inheritDoc}
     */
    public function getSede()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSede', array());

        return parent::getSede();
    }

    /**
     * {@inheritDoc}
     */
    public function setSede($sede)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSede', array($sede));

        return parent::setSede($sede);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', array());

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', array($observacion));

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermitir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermitir', array());

        return parent::getPermitir();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermitir($permitir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermitir', array($permitir));

        return parent::setPermitir($permitir);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecurso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecurso', array());

        return parent::getRecurso();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecurso($recurso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecurso', array($recurso));

        return parent::setRecurso($recurso);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocSustituto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocSustituto', array());

        return parent::getDocSustituto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocSustituto($docSustituto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocSustituto', array($docSustituto));

        return parent::setDocSustituto($docSustituto);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasRecuperadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasRecuperadas', array());

        return parent::getHorasRecuperadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorasRecuperadas($horasRecuperadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorasRecuperadas', array($horasRecuperadas));

        return parent::setHorasRecuperadas($horasRecuperadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getJustificaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJustificaciones', array());

        return parent::getJustificaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setJustificaciones($justificaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJustificaciones', array($justificaciones));

        return parent::setJustificaciones($justificaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', array());

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', array($version));

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getModulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModulo', array());

        return parent::getModulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setModulo($modulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModulo', array($modulo));

        return parent::setModulo($modulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmodulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmodulo', array());

        return parent::getSubmodulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmodulo($submodulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmodulo', array($submodulo));

        return parent::setSubmodulo($submodulo);
    }

}
