<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class JornadaIng extends \Entities\JornadaIng implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'ano', 'periodo', 'nivel', 'tipo', 'fecha', 'cupo', 'aula', 'hora', 'tipoExa', 'userCrea', 'fechaCrea', 'userMod', 'fechaMod');
        }

        return array('__isInitialized__', 'id', 'ano', 'periodo', 'nivel', 'tipo', 'fecha', 'cupo', 'aula', 'hora', 'tipoExa', 'userCrea', 'fechaCrea', 'userMod', 'fechaMod');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (JornadaIng $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAno', array());

        return parent::getAno();
    }

    /**
     * {@inheritDoc}
     */
    public function setAno($ano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAno', array($ano));

        return parent::setAno($ano);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodo', array());

        return parent::getPeriodo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodo($periodo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodo', array($periodo));

        return parent::setPeriodo($periodo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivel', array());

        return parent::getNivel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivel($nivel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivel', array($nivel));

        return parent::setNivel($nivel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getCupo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCupo', array());

        return parent::getCupo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCupo($cupo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCupo', array($cupo));

        return parent::setCupo($cupo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAula', array());

        return parent::getAula();
    }

    /**
     * {@inheritDoc}
     */
    public function setAula($aula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAula', array($aula));

        return parent::setAula($aula);
    }

    /**
     * {@inheritDoc}
     */
    public function getHora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora', array());

        return parent::getHora();
    }

    /**
     * {@inheritDoc}
     */
    public function setHora($hora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora', array($hora));

        return parent::setHora($hora);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoExa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoExa', array());

        return parent::getTipoExa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoExa($tipoExa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoExa', array($tipoExa));

        return parent::setTipoExa($tipoExa);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCrea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCrea', array());

        return parent::getUserCrea();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCrea($userCrea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCrea', array($userCrea));

        return parent::setUserCrea($userCrea);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCrea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCrea', array());

        return parent::getFechaCrea();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCrea($fechaCrea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCrea', array($fechaCrea));

        return parent::setFechaCrea($fechaCrea);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserMod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserMod', array());

        return parent::getUserMod();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserMod($userMod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserMod', array($userMod));

        return parent::setUserMod($userMod);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaMod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaMod', array());

        return parent::getFechaMod();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaMod($fechaMod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaMod', array($fechaMod));

        return parent::setFechaMod($fechaMod);
    }

}
