<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Estudiantes extends \Entities\Estudiantes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'codigo', 'cedula', 'tipoDocumento', 'lugarExpedicion', 'nombre1', 'nombre2', 'apellido1', 'apellido2');
        }

        return array('__isInitialized__', 'codigo', 'cedula', 'tipoDocumento', 'lugarExpedicion', 'nombre1', 'nombre2', 'apellido1', 'apellido2');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Estudiantes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', array());

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', array($codigo));

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCedula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCedula', array());

        return parent::getCedula();
    }

    /**
     * {@inheritDoc}
     */
    public function setCedula($cedula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCedula', array($cedula));

        return parent::setCedula($cedula);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDocumento', array());

        return parent::getTipoDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDocumento($tipoDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDocumento', array($tipoDocumento));

        return parent::setTipoDocumento($tipoDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarExpedicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarExpedicion', array());

        return parent::getLugarExpedicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugarExpedicion($lugarExpedicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugarExpedicion', array($lugarExpedicion));

        return parent::setLugarExpedicion($lugarExpedicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre1', array());

        return parent::getNombre1();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre1($nombre1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre1', array($nombre1));

        return parent::setNombre1($nombre1);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre2', array());

        return parent::getNombre2();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre2($nombre2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre2', array($nombre2));

        return parent::setNombre2($nombre2);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido1', array());

        return parent::getApellido1();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido1($apellido1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido1', array($apellido1));

        return parent::setApellido1($apellido1);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido2', array());

        return parent::getApellido2();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido2($apellido2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido2', array($apellido2));

        return parent::setApellido2($apellido2);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoYNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoYNombre', array());

        return parent::getCodigoYNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreCompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCompleto', array());

        return parent::getNombreCompleto();
    }

}
