<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Persona extends \Entities\Persona implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'cedula', 'nombre1', 'nombre2', 'apellido1', 'apellido2', 'nacionalidad', 'tipoDoc', 'lugarExp', 'tarjetaProfesional', 'sexo', 'estadoCivil', 'lugarNac', 'fechaNac', 'hijos', 'telefono1', 'telefono2', 'direccion', 'correoInst', 'correoPer', 'twitter', 'sitioWeb', 'facebook', 'direccionOficina', 'telefonoOficina', 'fechaExp');
        }

        return array('__isInitialized__', 'cedula', 'nombre1', 'nombre2', 'apellido1', 'apellido2', 'nacionalidad', 'tipoDoc', 'lugarExp', 'tarjetaProfesional', 'sexo', 'estadoCivil', 'lugarNac', 'fechaNac', 'hijos', 'telefono1', 'telefono2', 'direccion', 'correoInst', 'correoPer', 'twitter', 'sitioWeb', 'facebook', 'direccionOficina', 'telefonoOficina', 'fechaExp');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Persona $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTipoDoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDoc', array());

        return parent::getTipoDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function getCedula()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCedula();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCedula', array());

        return parent::getCedula();
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarExp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarExp', array());

        return parent::getLugarExp();
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido1', array());

        return parent::getApellido1();
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido2', array());

        return parent::getApellido2();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre1', array());

        return parent::getNombre1();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre2', array());

        return parent::getNombre2();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNac', array());

        return parent::getFechaNac();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaExp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaExp', array());

        return parent::getFechaExp();
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarNac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarNac', array());

        return parent::getLugarNac();
    }

    /**
     * {@inheritDoc}
     */
    public function getNacionalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNacionalidad', array());

        return parent::getNacionalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', array());

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoCivil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoCivil', array());

        return parent::getEstadoCivil();
    }

    /**
     * {@inheritDoc}
     */
    public function getHijos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHijos', array());

        return parent::getHijos();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono1', array());

        return parent::getTelefono1();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono2', array());

        return parent::getTelefono2();
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreoInst()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreoInst', array());

        return parent::getCorreoInst();
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreoPer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreoPer', array());

        return parent::getCorreoPer();
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', array());

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function getSitioWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSitioWeb', array());

        return parent::getSitioWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebook', array());

        return parent::getFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function getTarjetaProfesional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarjetaProfesional', array());

        return parent::getTarjetaProfesional();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDoc(\Entities\TipoDocumento $tipoDoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDoc', array($tipoDoc));

        return parent::setTipoDoc($tipoDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function setCedula($cedula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCedula', array($cedula));

        return parent::setCedula($cedula);
    }

    /**
     * {@inheritDoc}
     */
    public function setLugarExp($lugarExp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugarExp', array($lugarExp));

        return parent::setLugarExp($lugarExp);
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido1($apellido1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido1', array($apellido1));

        return parent::setApellido1($apellido1);
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido2($apellido2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido2', array($apellido2));

        return parent::setApellido2($apellido2);
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre1($nombre1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre1', array($nombre1));

        return parent::setNombre1($nombre1);
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre2($nombre2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre2', array($nombre2));

        return parent::setNombre2($nombre2);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNac($fechaNac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNac', array($fechaNac));

        return parent::setFechaNac($fechaNac);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaExp($fechaExp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaExp', array($fechaExp));

        return parent::setFechaExp($fechaExp);
    }

    /**
     * {@inheritDoc}
     */
    public function setLugarNac($lugarNac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugarNac', array($lugarNac));

        return parent::setLugarNac($lugarNac);
    }

    /**
     * {@inheritDoc}
     */
    public function setNacionalidad(\Entities\Pais $nacionalidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNacionalidad', array($nacionalidad));

        return parent::setNacionalidad($nacionalidad);
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', array($sexo));

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoCivil(\Entities\EstadoCivil $estadoCivil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoCivil', array($estadoCivil));

        return parent::setEstadoCivil($estadoCivil);
    }

    /**
     * {@inheritDoc}
     */
    public function setHijos($hijos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHijos', array($hijos));

        return parent::setHijos($hijos);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono1($telefono1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono1', array($telefono1));

        return parent::setTelefono1($telefono1);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono2($telefono2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono2', array($telefono2));

        return parent::setTelefono2($telefono2);
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreoInst($correoInst)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreoInst', array($correoInst));

        return parent::setCorreoInst($correoInst);
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreoPer($correoPer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreoPer', array($correoPer));

        return parent::setCorreoPer($correoPer);
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($twitter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', array($twitter));

        return parent::setTwitter($twitter);
    }

    /**
     * {@inheritDoc}
     */
    public function setSitioWeb($sitioWeb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSitioWeb', array($sitioWeb));

        return parent::setSitioWeb($sitioWeb);
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebook($facebook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebook', array($facebook));

        return parent::setFacebook($facebook);
    }

    /**
     * {@inheritDoc}
     */
    public function setTarjetaProfesional($tarjetaProfesional)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarjetaProfesional', array($tarjetaProfesional));

        return parent::setTarjetaProfesional($tarjetaProfesional);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreCompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCompleto', array());

        return parent::getNombreCompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccionOficina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccionOficina', array());

        return parent::getDireccionOficina();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccionOficina($direccionOficina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccionOficina', array($direccionOficina));

        return parent::setDireccionOficina($direccionOficina);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoOficina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoOficina', array());

        return parent::getTelefonoOficina();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoOficina($telefonoOficina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoOficina', array($telefonoOficina));

        return parent::setTelefonoOficina($telefonoOficina);
    }

}
