<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Estado extends \Entities\Estado implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'epano', 'epsem', 'ecprog', 'ecest', 'esem', 'egrupo', 'ejor', 'eestad', 'enmp', 'enmv', 'estpro', 'estsac', 'esthab');
        }

        return array('__isInitialized__', 'epano', 'epsem', 'ecprog', 'ecest', 'esem', 'egrupo', 'ejor', 'eestad', 'enmp', 'enmv', 'estpro', 'estsac', 'esthab');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Estado $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getEpano()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getEpano();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpano', array());

        return parent::getEpano();
    }

    /**
     * {@inheritDoc}
     */
    public function setEpano($epano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpano', array($epano));

        return parent::setEpano($epano);
    }

    /**
     * {@inheritDoc}
     */
    public function getEpsem()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getEpsem();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpsem', array());

        return parent::getEpsem();
    }

    /**
     * {@inheritDoc}
     */
    public function setEpsem($epsem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpsem', array($epsem));

        return parent::setEpsem($epsem);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcprog()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getEcprog();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcprog', array());

        return parent::getEcprog();
    }

    /**
     * {@inheritDoc}
     */
    public function setEcprog($ecprog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEcprog', array($ecprog));

        return parent::setEcprog($ecprog);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcest()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getEcest();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcest', array());

        return parent::getEcest();
    }

    /**
     * {@inheritDoc}
     */
    public function setEcest($ecest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEcest', array($ecest));

        return parent::setEcest($ecest);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsem', array());

        return parent::getEsem();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsem($esem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsem', array($esem));

        return parent::setEsem($esem);
    }

    /**
     * {@inheritDoc}
     */
    public function getEgrupo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEgrupo', array());

        return parent::getEgrupo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEgrupo($egrupo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEgrupo', array($egrupo));

        return parent::setEgrupo($egrupo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEjor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEjor', array());

        return parent::getEjor();
    }

    /**
     * {@inheritDoc}
     */
    public function setEjor($ejor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEjor', array($ejor));

        return parent::setEjor($ejor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEestad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEestad', array());

        return parent::getEestad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEestad($eestad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEestad', array($eestad));

        return parent::setEestad($eestad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnmp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnmp', array());

        return parent::getEnmp();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnmp($enmp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnmp', array($enmp));

        return parent::setEnmp($enmp);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnmv', array());

        return parent::getEnmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnmv($enmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnmv', array($enmv));

        return parent::setEnmv($enmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstpro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstpro', array());

        return parent::getEstpro();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstpro($estpro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstpro', array($estpro));

        return parent::setEstpro($estpro);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstsac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstsac', array());

        return parent::getEstsac();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstsac($estsac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstsac', array($estsac));

        return parent::setEstsac($estsac);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsthab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsthab', array());

        return parent::getEsthab();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsthab($esthab)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsthab', array($esthab));

        return parent::setEsthab($esthab);
    }

}
